---
title: "Economia Naranja"
author: "Zugey Castillo"
date: "17 de junio de 2021"
output: html_document
---

```{r}
orangeec <- read.csv("/Users/DarioJaciel/Desktop/Zuky/Rstudio/orangeec.csv")
data(orangeec)
summary(orangeec)
#Otra forma de agregar un espacio Chunk es dar click en Insert > R
```
Este es un comentario:  
Parece que hay correlación entre aporte de economía naranja al PIB y la tasa de desempleo
```{r}
pairs(orangeec[,6:10])
```
```{r}
library(ggplot2)
```
```{r}
ggplot() + geom_histogram(data = orangeec,
                          aes(x = Internet.penetration...population),
                          fill = "light blue", color="black",
                          binwidth = 5) +
  scale_x_continuous(breaks = seq(40, max(100), 5)) +
  labs(x = "Penetración de internet (%) por población", y = "Cantidad de países",
       title = "Penetración de internet en LATAM") +
  theme(legend.position = "none") +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
```
```{r}
library(dplyr)
```
```{r}
economia <- mean(orangeec$GDP.PC)
economia
```
```{r}
orangeec <- orangeec %>%
  mutate(Strong_economy = ifelse(GDP.PC < economia,
                                 "Por debajo del promedio PIB per cápita",
                                 "Por arriba del promedio PIB per cápita"))
```
```{r}
ggplot(orangeec, aes(x = Strong_economy, y = Creat.Ind...GDP,
                     fill = Strong_economy)) + 
  geom_boxplot(alpha = 0.4) +
  labs(x = "Tipo de país", y = "Aporte economía naranja al PIB",
       title = "Aporte economía naranja al PIB LATAM con alto y bajo PIB per cápita") + 
  theme(legend.position = "none") +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
```
  
El boxplot indica que los países sobre el promedio del PIB per cápita tienen una dispersión mucho más alta en cuanto a los aportes de la economía naranja al PIB del país.  
  
NOTA: Confirmar con desviación estándar.
